### PR TITLE
Support for mongoid 5

### PR DESCRIPTION
**Pull request by deepredsky**
minor changes to use mongoid 5 beta

### CODE REVIEW

**Comment by simi** [comment]
Thanks for this patch. Mongoid 5 is not released yet, but I can make a feature branch for this to be prepared to release new version once Mongoid 5 will be out.

**Comment by deepredsky** [comment]
Sounds good. I created the PR since I had to patch the code to use in one of my projects. Cheers!

**Comment by johnnyshields** [comment]
@simi, since this plugin is relatively small and not changing a whole lot, I think we should just make an entirely new version of MongoidParanoia that doesn't support Mongoid 4. What do you think?

**Comment by simi** [comment]
@johnnyshields If the only change is to use `update_one` instead of `update`, I think we can support both 4 and 5 in one version.

**Comment by simi** [comment]
@johnnyshields ahh sorry, I missed your idea. I was about to create new major version also. But I thought you're not fan of that. Sure we can do that.

**Comment by dblock** [comment]
This should be closed in favor of https://github.com/simi/mongoid_paranoia/pull/38.

**Pull request closed without merging**
