### PR TITLE
minor 0.2.0 #noissue

### PR DESCRIPTION
**Pull request by ak47**
Hey guys, how about a release?  it's been just over a year since the last one

The CHANGELOG added follows this pattern: http://keepachangelog.com

Also went with 0.2.0 following http://semver.org : "MINOR version when you add functionality in a backwards-compatible manner"

### CODE REVIEW

**Comment by simi** [comment]
Thanks for your interest @ak47!

I think we can remove this from changelog and move it to README.md (:question:)

```
# Change Log
All notable changes to this project will be documented in this file.
This project adheres to [Semantic Versioning](http://semver.org/).
```

@johnnyshields do you think 0.2.0 is prepared to be out?

**Comment by johnnyshields** [comment]
Looks good to me :+1:

**Comment by simi** [comment]
I think we can use simple CHANGELOG format like https://github.com/refinery/refinerycms/blob/master/changelog.md.

@ak47 would you mind to change it?

**Comment by ak47** [comment]
updated CHANGELOG format,  does that work?

Kind of guessed at the unreleased version (1.0.0).

Also left out the bit about semver.org entirely, seems like that can go without saying - unless someone thinks it needs to be explicit.

**Comment by dblock** [comment]
I've added a CHANGELOG in https://github.com/simi/mongoid_paranoia/pull/38, I think this should be closed in favor of that one.

**Comment by johnnyshields** [comment]
Closing as #38 has been merged instead.

**Pull request closed without merging**
