### PR TITLE
Don't override mongoid original update.

### LINKED ISSUE #39: including Mongoid::Paranoia changes the update method from public to private
```ruby
class Human
  include Mongoid::Document
end
human = Human.create #=> #<Human _id: 5605a9a71942d01471000002, >
human.update #=> true
Mongoid::Compatibility::Version.mongoid5? #=> true
class Robot
  include Mongoid::Document
  include Mongoid::Paranoia
end
robot = Robot.create #=> #<Robot _id: 5605a9d11942d01471000003, deleted_at(deleted_at): nil>
robot.update
# NoMethodError: private method `update' called for #<Robot:0x00000103c2ecd8>
```

The update method: https://github.com/mongodb/mongoid/blob/ffad088b8c75390d01424494f17eb25ac285db90/lib/mongoid/persistable/updatable.rb#L40-L54

### PR DESCRIPTION
**Pull request by simi**
fixes #39

### CODE REVIEW

**Comment by dblock** [comment]
It needs an entry in https://github.com/simi/mongoid_paranoia/blob/master/CHANGELOG.md, please. And do write a test. It's contrived, but good discipline.

**Comment by simi** [comment]
Yes, but it is hard to write proper test for this. I can open some regression test spec file for those cases. But I don't want to write `update` test again, since there's one in Mongoid test suite.

What about the test case testing paranoia is not overriding methods except those we want (like destroy) :question: That should cover this problem and the future unwanted overrides.

**Comment by maxjacobson** [comment]
That sounds like a good approach to me!

**Comment by dblock** [comment]
:+1:

**Comment by simi** [comment]
@maxjacobson @dblock this was released as `0.2.1`. I'll open issue for the rest (testing the overriding).

**Comment by maxjacobson** [comment]
Thanks @simi

**Comment by simi** [comment]
Thanks for the report!

**Pull request merged**
