### PR TITLE
Mongoid 7 support

### PR DESCRIPTION
**Pull request by ktanaka777**
It support only Mongoid 7, but I am happy if it helps you.

### CODE REVIEW

**Comment by simi** [comment]
Thanks for this PR. Do you have any idea why CI is failing? https://travis-ci.org/simi/mongoid_paranoia/jobs/396686562

**Comment by ktanaka777** [comment]
> Thanks for this PR. Do you have any idea why CI is failing? https://travis-ci.org/simi/mongoid_paranoia/jobs/396686562

You can resolve this failure by PR https://github.com/simi/mongoid_paranoia/pull/52

**Comment by ktanaka777** [comment]
But I don't have an idea for this failure https://travis-ci.org/simi/mongoid_paranoia/jobs/396686564

**Comment by stanley90** [comment]
Hi, how is this going? Is help needed?

**Comment by simi** [comment]
should be released now, closing

**Pull request closed without merging**
