### PR TITLE
Added 'removal' callbacks that run exclusively on permanent removal

### PR DESCRIPTION
**Pull request by marcelloma**
Hey,

I needed a callback that ran exclusively when the document gets "hard" removed so I created one. I didn't have a great name for it so I called it removal. Please take a look and tell me your thoughts. If everything is ok I will be happy to update docs including this.

### CODE REVIEW

**Comment by marcelloma** [comment]
@simi after_destroy runs on both soft and hard deletes. after_removal runs only on hard delete. @johnnyshields after_remove is a much better name indeed, I didn't know the actual method was remove(I use destroy! to hard delete).

**Comment by johnnyshields** [comment]
The code is a bit hard to read because of `alias_method_chain` usage (yuck!) but basically `remove` is same as `delete` and `remove_without_paranoia` is the same as `delete!`. So technically speaking `remove` method does **not** hard-delete doc, but it's still ok I think to name callback `after_remove`

**Comment by johnnyshields** [comment]
Also, please be sure to update the readme please

**Comment by marcelloma** [comment]
I've updated the readme and changed the of the callback to remove.

**Comment by simi** [comment]
I can't see difference in tests for `remove` and `delete` callbacks. :(

**Comment by marcelloma** [comment]
@simi If you read the specs you will see the difference. Remove is only called when the mongodb document is actually deleted, not flagged with deleted_at. Destroy is called when a document is destroyed, and with mongoid-paranoia it means flagged with deleted_at.

**Comment by marcelloma** [comment]
@simi 
```ruby
describe "#destroy" do
       # Here we check for if the destroy callback was called
       it "executes the before destroy callbacks" do
        expect(post.before_destroy_called).to be_truthy
      end

      it "executes the after destroy callbacks" do
        expect(post.after_destroy_called).to be_truthy
      end

     # Here we check for if the REMOVE callback was NOT called
      it "does not execute the before remove callbacks" do
        expect(post.before_remove_called).to be_falsey
      end

      it "does not execute the after remove callbacks" do
        expect(post.after_remove_called).to be_falsey
      end
end
```

The describe "#destroy!" is equal because when destroy! is called both callbacks are fired, the difference resides in when "#destroy" is called.

**Comment by simi** [comment]
OK, thanks for info.

@johnnyshields feel free to merge.

**Comment by johnnyshields** [comment]
Looks good to me!

**Pull request merged**
