### PR TITLE
Support mongoid 7

### PR DESCRIPTION
**Pull request by tagliala**
This PR includes:
- #52 
- #54 
- #60

I've also bumped version to 0.4.0 and updated changelog

### CODE REVIEW

**Comment by rubydev** [comment]
@simi Could you please merge this PR? Thanks!

**Comment by spatino** [comment]
@simi some news about merge this PR? Thanks!

**Comment by simi** [comment]
@spatino thanks for reminder. I'll check if everything is ok and release later today.

**Comment by radar** [comment]
@simi Do you need some help with this release?

**Comment by radar** [comment]
@simi Could you please release 0.4.0 with the latest commits?

**Comment by simi** [comment]
@radar sorry for the delay, it was released few minutes ago.

**Pull request merged**
