### PR TITLE
[WIP] Rails 5.0.0.rc1 support

### PR DESCRIPTION
**Pull request by Fudoshiki**
Target master branch at Mongoid HEAD with refactor code base

### CODE REVIEW

**Comment by simi** [comment]
Are we dropping 1.9.3 with this?

**Comment by Fudoshiki** [comment]
Yse. Rails 5.0.0.rc1 and mongoid HEAD require ruby >= 2.2.2

**Comment by simi** [comment]
OK, that makes sense.

To summarize all changes:

1. rubocob.yml added, but actually it is not used
2. quoting changed
3. CI mongodb version changed
4. .versions.conf added
5. mongoid version forced to 6
6. code updated to support only monogoid 6
7. notifications are disabled on CI

I think we can skip 1,2,4 and 7 for this change. We can introduce rubocop in separate PR, but I don't see any benefit in that.

If minimal mongodb (3) or mongoid (5, 6) versions are affected we need to bump major version level. With this change we can drop mongoid-compatibility gem dependency probably also.

:heart: Thanks for bringing this up. :heart: 
Ping me if you're able to work on those changes. I can try to finish this also on my own if you'll be not able.

**Comment by Fudoshiki** [comment]
@simi 

**WIP**
- [ ] Travis setup, target Mongoid HEAD and look on failed tests
- [ ] Remove useless code and dependencies for Mongoid HEAD
- [ ] Fix test

If .rubocop.yml and .versions.conf dont't need, we should add lines in .gitignore

So, maybe close this PR and start new with rebased commits in one?

**Comment by simi** [comment]
@Fudoshiki feel free to force push here.

> If .rubocop.yml and .versions.conf dont't need, we should add lines in .gitignore

I think that's something you can do localy (in global gitignore?) because it is not related to this codebase (those are files generated by tools installed in your system only).

**Comment by Fudoshiki** [comment]
@simi We can make better with add in .gitignore lines

.*
!./.gitignore
!/.rspec
!/.travis.yml

**Comment by Fudoshiki** [comment]
I will rebase my PR here and start work on refactoring

**Comment by Fudoshiki** [comment]
Continue here https://github.com/simi/mongoid_paranoia/pull/45

**Pull request closed without merging**
